---
branches:
  - main

tagFormat: '${version}'

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/npm'
  - '@semantic-release/github'
  - '@semantic-release/git'

changelogFile: CHANGELOG.md

# Automatische Commit-Nachricht für den Changelog und Versions-Updates
git:
  assets:
    - main.js
    - manifest.json
    - style.css
  message: 'chore(release): ${nextRelease.version} [skip ci]'