name: Release Obsidian Plugin

on:
    push:
        branches:
            - main

jobs:
    build-and-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Build plugin
              run: npm run build

            # - name: Create release zip
            #   run: |
            #       mkdir release
            #       cp manifest.json release/
            #       cp main.js release/
            #       [ -f styles.css ] && cp styles.css release/
            #       cd release
            #       zip ../obsidian-current-view.zip *

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2.2.2
              with:
                  files: |
                      main.js
                      manifest.json
                      styles.css
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    semantic-release:
        needs: build-and-release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install dependencies
              run: npm ci

            - name: Run Semantic Release
              uses: cycjimmy/semantic-release-action@v4
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
